
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package in.com;

public class App {
    public String getGreeting() {


        return "welcome in gradle project";  
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
